// AUTO-GENERATED by scripts/derive_avatar_profiles.py -- do not hand-edit.
// Regenerate by rerunning the script against public/avatars/*.png.
import type { AvatarGeometry } from "./avatarGeometry";

export type AvatarProfile = AvatarGeometry & {
  id: string;
  displayName: string;
  smileKey: string;
  frownKey: string;
  smileSrc: string;
  frownSrc: string;
};

export const AVATAR_PROFILES: AvatarProfile[] = [
  {
    id: "rebecca", displayName: "Rebecca",
    smileKey: "avatar-rebecca-smile", frownKey: "avatar-rebecca-frown",
    smileSrc: "/avatars/rebecca-smile.png", frownSrc: "/avatars/rebecca-frown.png",
    eyeLocal: { left: { x: 144.6, y: 263.0 }, right: { x: 215.0, y: 263.0 } },
    scleraHeightLocal: 14.0,
    shoulderLocal: { left: { x: 35.5, y: 473.0 }, right: { x: 324.0, y: 473.0 } },
    armColor: 0x2f302f, skinColor: 0xe5b89b, irisColor: 0x3f2a17,
  },
  {
    id: "andy", displayName: "Andy",
    smileKey: "avatar-andy-smile", frownKey: "avatar-andy-frown",
    smileSrc: "/avatars/andy-smile.png", frownSrc: "/avatars/andy-frown.png",
    eyeLocal: { left: { x: 144.4, y: 253.2 }, right: { x: 214.7, y: 253.2 } },
    scleraHeightLocal: 10.5,
    shoulderLocal: { left: { x: 37.0, y: 476.0 }, right: { x: 322.0, y: 476.0 } },
    armColor: 0x7a7e5c, skinColor: 0xdd9b78, irisColor: 0x8a6d3f,
  },
  {
    id: "terri", displayName: "Terri",
    smileKey: "avatar-terri-smile", frownKey: "avatar-terri-frown",
    smileSrc: "/avatars/terri-smile.png", frownSrc: "/avatars/terri-frown.png",
    eyeLocal: { left: { x: 144.7, y: 219.2 }, right: { x: 215.2, y: 219.2 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 16.5, y: 458.0 }, right: { x: 343.0, y: 458.0 } },
    armColor: 0x436375, skinColor: 0xf5c3aa, irisColor: 0x3f2a17,
  },
  {
    id: "gus", displayName: "Gus",
    smileKey: "avatar-gus-smile", frownKey: "avatar-gus-frown",
    smileSrc: "/avatars/gus-smile.png", frownSrc: "/avatars/gus-frown.png",
    eyeLocal: { left: { x: 144.2, y: 252.5 }, right: { x: 214.6, y: 252.5 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 36.5, y: 476.0 }, right: { x: 322.0, y: 476.0 } },
    armColor: 0x5e7b98, skinColor: 0xe5aa8c, irisColor: 0x4a7ab5,
  },
  {
    id: "claudia", displayName: "Claudia",
    smileKey: "avatar-claudia-smile", frownKey: "avatar-claudia-frown",
    smileSrc: "/avatars/claudia-smile.png", frownSrc: "/avatars/claudia-frown.png",
    eyeLocal: { left: { x: 145.1, y: 227.4 }, right: { x: 215.6, y: 227.4 } },
    scleraHeightLocal: 10.0,
    shoulderLocal: { left: { x: 7.5, y: 469.0 }, right: { x: 352.5, y: 469.0 } },
    armColor: 0xe1ad87, skinColor: 0xe2ad85, irisColor: 0x4a7ab5,
  },
  {
    id: "abe", displayName: "Abe",
    smileKey: "avatar-abe-smile", frownKey: "avatar-abe-frown",
    smileSrc: "/avatars/abe-smile.png", frownSrc: "/avatars/abe-frown.png",
    eyeLocal: { left: { x: 144.7, y: 213.4 }, right: { x: 215.2, y: 212.7 } },
    scleraHeightLocal: 10.25,
    shoulderLocal: { left: { x: 14.5, y: 463.0 }, right: { x: 344.5, y: 463.0 } },
    armColor: 0x272727, skinColor: 0xf0bda2, irisColor: 0x3f2a17,
  },
  {
    id: "matt", displayName: "Matt",
    smileKey: "avatar-matt-smile", frownKey: "avatar-matt-frown",
    smileSrc: "/avatars/matt-smile.png", frownSrc: "/avatars/matt-frown.png",
    eyeLocal: { left: { x: 144.3, y: 264.0 }, right: { x: 214.7, y: 264.0 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 40.5, y: 480.0 }, right: { x: 319.0, y: 480.0 } },
    armColor: 0xf9ceb5, skinColor: 0xfbcdb5, irisColor: 0x4a7ab5,
  },
  {
    id: "mj", displayName: "MJ",
    smileKey: "avatar-mj-smile", frownKey: "avatar-mj-frown",
    smileSrc: "/avatars/mj-smile.png", frownSrc: "/avatars/mj-frown.png",
    eyeLocal: { left: { x: 144.3, y: 284.0 }, right: { x: 214.8, y: 284.0 } },
    scleraHeightLocal: 12.0,
    shoulderLocal: { left: { x: 45.0, y: 478.0 }, right: { x: 314.0, y: 478.0 } },
    armColor: 0x347d8f, skinColor: 0xa85c35, irisColor: 0x3f2a17,
  },
  {
    id: "nichole", displayName: "Nichole",
    smileKey: "avatar-nichole-smile", frownKey: "avatar-nichole-frown",
    smileSrc: "/avatars/nichole-smile.png", frownSrc: "/avatars/nichole-frown.png",
    eyeLocal: { left: { x: 145.0, y: 246.3 }, right: { x: 215.3, y: 246.3 } },
    scleraHeightLocal: 12.5,
    shoulderLocal: { left: { x: 23.5, y: 467.0 }, right: { x: 336.5, y: 467.0 } },
    armColor: 0x63a8c1, skinColor: 0xf1c0a2, irisColor: 0x5c7d4f,
  },
];
