// AUTO-GENERATED by scripts/derive_avatar_profiles.py -- do not hand-edit.
// Regenerate by rerunning the script against public/avatars/*.png.
import type { AvatarGeometry } from "./avatarGeometry";

export type AvatarProfile = AvatarGeometry & {
  id: string;
  displayName: string;
  smileKey: string;
  frownKey: string;
  smileSrc: string;
  frownSrc: string;
};

export const AVATAR_PROFILES: AvatarProfile[] = [
  {
    id: "traci", displayName: "Traci",
    smileKey: "avatar-traci-smile", frownKey: "avatar-traci-frown",
    smileSrc: "/avatars/traci-smile.png", frownSrc: "/avatars/traci-frown.png",
    eyeLocal: { left: { x: 145.0, y: 205.0 }, right: { x: 215.4, y: 204.9 } },
    scleraHeightLocal: 11.1,
    shoulderLocal: { left: { x: 8.0, y: 482.0 }, right: { x: 359.5, y: 482.0 } },
    // Auto-detected iris color came back near-white (glasses-lens reflection interfering
    // with the sample), so this uses the same green already established for Nichole
    // instead, per direct confirmation that Traci's eyes are green.
    armColor: 0xe7a781, skinColor: 0xe9a57e, irisColor: 0x5c7d4f,
  },
  {
    id: "andy", displayName: "Andy",
    smileKey: "avatar-andy-smile", frownKey: "avatar-andy-frown",
    smileSrc: "/avatars/andy-smile.png", frownSrc: "/avatars/andy-frown.png",
    eyeLocal: { left: { x: 144.4, y: 253.2 }, right: { x: 214.7, y: 253.2 } },
    scleraHeightLocal: 10.5,
    shoulderLocal: { left: { x: 37.0, y: 476.0 }, right: { x: 322.0, y: 476.0 } },
    armColor: 0x7a7e5c, skinColor: 0xdd9b78, irisColor: 0x8a6d3f,
  },
  {
    id: "terri", displayName: "Terri",
    smileKey: "avatar-terri-smile", frownKey: "avatar-terri-frown",
    smileSrc: "/avatars/terri-smile.png", frownSrc: "/avatars/terri-frown.png",
    eyeLocal: { left: { x: 144.7, y: 219.2 }, right: { x: 215.2, y: 219.2 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 16.5, y: 458.0 }, right: { x: 343.0, y: 458.0 } },
    armColor: 0x436375, skinColor: 0xf5c3aa, irisColor: 0x3f2a17,
  },
  {
    id: "gus", displayName: "Gus",
    smileKey: "avatar-gus-smile", frownKey: "avatar-gus-frown",
    smileSrc: "/avatars/gus-smile.png", frownSrc: "/avatars/gus-frown.png",
    eyeLocal: { left: { x: 144.2, y: 252.5 }, right: { x: 214.6, y: 252.5 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 36.5, y: 476.0 }, right: { x: 322.0, y: 476.0 } },
    armColor: 0x5e7b98, skinColor: 0xe5aa8c, irisColor: 0x4a7ab5,
  },
  {
    id: "carrie", displayName: "Carrie",
    smileKey: "avatar-carrie-smile", frownKey: "avatar-carrie-frown",
    smileSrc: "/avatars/carrie-smile.png", frownSrc: "/avatars/carrie-frown.png",
    eyeLocal: { left: { x: 145.0, y: 214.4 }, right: { x: 215.5, y: 214.4 } },
    scleraHeightLocal: 11.11,
    shoulderLocal: { left: { x: 7.5, y: 458.0 }, right: { x: 353.0, y: 458.0 } },
    // Auto-detected iris color isn't used here -- confirmed directly: Carrie's eyes are
    // dark blue.
    armColor: 0xb7d1ec, skinColor: 0xfcbc99, irisColor: 0x1e3a5f,
  },
  {
    id: "matt", displayName: "Matt",
    smileKey: "avatar-matt-smile", frownKey: "avatar-matt-frown",
    smileSrc: "/avatars/matt-smile.png", frownSrc: "/avatars/matt-frown.png",
    eyeLocal: { left: { x: 144.3, y: 264.0 }, right: { x: 214.7, y: 264.0 } },
    scleraHeightLocal: 11.5,
    shoulderLocal: { left: { x: 40.5, y: 480.0 }, right: { x: 319.0, y: 480.0 } },
    armColor: 0xf9ceb5, skinColor: 0xfbcdb5, irisColor: 0x4a7ab5,
  },
  {
    id: "abe", displayName: "Abe",
    smileKey: "avatar-abe-smile", frownKey: "avatar-abe-frown",
    smileSrc: "/avatars/abe-smile.png", frownSrc: "/avatars/abe-frown.png",
    eyeLocal: { left: { x: 144.7, y: 213.4 }, right: { x: 215.2, y: 212.7 } },
    scleraHeightLocal: 10.25,
    shoulderLocal: { left: { x: 14.5, y: 463.0 }, right: { x: 344.5, y: 463.0 } },
    armColor: 0x272727, skinColor: 0xf0bda2, irisColor: 0x3f2a17,
  },
  {
    id: "mj", displayName: "MJ",
    smileKey: "avatar-mj-smile", frownKey: "avatar-mj-frown",
    smileSrc: "/avatars/mj-smile.png", frownSrc: "/avatars/mj-frown.png",
    eyeLocal: { left: { x: 144.3, y: 284.0 }, right: { x: 214.8, y: 284.0 } },
    scleraHeightLocal: 12.0,
    shoulderLocal: { left: { x: 45.0, y: 478.0 }, right: { x: 314.0, y: 478.0 } },
    armColor: 0x347d8f, skinColor: 0xa85c35, irisColor: 0x3f2a17,
  },
  {
    id: "alysa", displayName: "Alysa",
    smileKey: "avatar-alysa-smile", frownKey: "avatar-alysa-frown",
    smileSrc: "/avatars/alysa-smile.png", frownSrc: "/avatars/alysa-frown.png",
    eyeLocal: { left: { x: 144.7, y: 238.6 }, right: { x: 215.2, y: 238.5 } },
    scleraHeightLocal: 13.2,
    shoulderLocal: { left: { x: 24.0, y: 469.0 }, right: { x: 335.5, y: 469.0 } },
    // Auto-detected iris color came back near-white (0xfefefe -- no glasses this time, but
    // still not a usable read), so this falls back to the same brown default most other
    // avatars share, matching derive_avatar_profiles.py's own DEFAULT_IRIS_COLOR.
    armColor: 0xf0c6ad, skinColor: 0xf2c6ad, irisColor: 0x3f2a17,
  },
];
